### ISSUE TITLE
Incorrect output?

### ISSUE THREAD

**Issue by robintema** [ZoomerAnalytics/jsondiff#4]
Hi,
  I am using jsondiff in a django project where I save some data in json format into the database. Basically the json is a list of dictionaries: [{"name":"James"},{"name":"John"}]

When I receive a new json in the request this is the way I try to get the json changes:
```python
old = '[{}]'
new = '[{"name":"James"}]'

difference = diff(old, new, load=True, syntax='symmetric')
```

What I would expect as the value for difference is something like this:
```python
{insert: [(0, {'name': 'James'})]}
```
but I got this:
```python
[[{}], [{'name': 'James'}]]
```

Is this the correct behaviour?

**Comment by ericremoreynolds** [comment]
Hi Norbert,

Jsondiff can output diffs in various syntaxes, here you have selected the
'symmetric' syntax and the output is correct in this case. Perhaps you are
looking for the default 'compact' syntax?

Rgds

Eric

**Comment by robintema** [comment]
Hi Eric,

thanks for your answer. The problem with the default syntax is  that it does not return (at least in some cases) what was deleted, added:
For example:
```python
old = '[{}]'
new = '[{"name":"James"}]'
```
will return:
```python
[{'name': 'James'}]
```
So I guess it returns what is new. Then if I try this:
```python
old = '[{"t":"fr"}]'
new = '[{"name":"Jamesy"},{"another":"yes"}]'
```
it returns:
```python
[{'name': 'Jamesy'}, {'another': 'yes'}]
```
and I don't get what was removed from the json.

Regards,
Norbert.

**Comment by robintema** [comment]
I have tried the symmetric syntax with complex example that has all the possible changes that might occur. In the below example I got exactly what I wanted:
```python
old = '[{"first": "1", "first1": "11","first2":"111"},{"to_remove":2}]'
new = '[{"first": "1", "first1": "updated", "first3":"new", "first4":"4"},{"second":"2"},{"third":3}]'
```
The jsondiff of the above (with 'symmetric' syntax) will be:
```python   
{
    0: {
        delete: {'first2': '111'},
        insert: {'first3': 'new', 'first4': '4'},
        'first1': ['11', 'updated']
        },
    delete: [(1, {'to_remove': 2})],
    insert: [(1, {'second': '2'}), (2, {'third': 3})]
}
```

**Comment by ericremoreynolds** [comment]
Ah I see what you mean now. So, the output is 'correct' in the sense that the following works correctly:

    from jsondiff import diff, patch
    old = [{}]
    new = [{"name":"James"}]
    difference = diff(old, new, syntax='symmetric')
    new == patch(old, difference, syntax='symmetric')

though I can understand if you, for whatever reason, would want something different. [Here](https://github.com/ZoomerAnalytics/jsondiff/blob/master/jsondiff/__init__.py#L220) you can see in the implementation of the symmetric syntax why it's giving that output. What's happening is that the algorithm thinks there's no similarity between the lists, so instead of representing the changes as a 'patch' it represents them as a 'substitution'. In the symmetric syntax `[a, b]` just means that `a` got replaced with `b`.

The root cause is the fact that jsondiff considers

    similarity({}, {'name': 'James'}) == 0

and since there is no functionality right now to override the similarity function, if you want different behaviour you'll have to get your hands dirty on the jsondiff code!

Let me know if this cleared up the issue for you.

Eric

**Comment by ericremoreynolds** [comment]
Actually perhaps I spoke too soon, it may be possible to achieve different behaviour by writing your own 'syntax' class, for example subclass `SymmetricJsonDiffSyntax` and override `emit_list_diff` to ignore the similarity `s` and always emit a patch-style diff.

You should then be able to pass your syntax like this:

    difference = diff(old, new, syntax=MySyntaxClass)

**Comment by robintema** [comment]
Thank you, I will try it and let you know if it is working.

**Comment by robintema** [comment]
It is working, thanks for you help.
The working code:
```python
class MySymmetricJsonDiffSyntax(SymmetricJsonDiffSyntax):

    def emit_list_diff(self, a, b, s, inserted, changed, deleted):
        # if s == 0.0:
        #     return [a, b]
        # elif s == 1.0:
        #     return {}
        # else:
        d = changed
        if inserted:
            d[insert] = inserted
        if deleted:
            d[delete] = deleted
        return d

difference = diff(old, new, load=True, syntax=MySymmetricJsonDiffSyntax())
```
